create table if not exists write_idempotency_records (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    operation varchar(80) not null,
    idempotency_key varchar(160) not null,
    status varchar(40) not null,
    resource_id bigint,
    created_at varchar(40) not null,
    updated_at varchar(40) not null,
    constraint fk_write_idempotency_member
        foreign key (member_id) references auth_members(id)
        on delete cascade,
    constraint uq_write_idempotency_member_operation_key
        unique (member_id, operation, idempotency_key)
);

create index if not exists idx_write_idempotency_updated
    on write_idempotency_records(status, updated_at);
