create table if not exists auth_password_reset_tokens (
    id bigint generated by default as identity primary key,
    request_key_hash varchar(128) not null,
    member_id bigint,
    token_hash varchar(128) not null unique,
    expires_at varchar(40) not null,
    consumed_at varchar(40),
    failed_attempts integer not null default 0,
    created_at varchar(40) not null,
    constraint fk_auth_password_reset_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_auth_password_reset_request_active
    on auth_password_reset_tokens(request_key_hash, consumed_at, expires_at);
