create table if not exists diary_content_blocks (
    id bigint generated by default as identity primary key,
    diary_id bigint not null,
    client_block_id varchar(120) not null,
    block_type varchar(20) not null,
    display_order integer not null,
    text_content text,
    image_url varchar(1000),
    filename varchar(255),
    byte_size bigint,
    source varchar(40),
    content_type varchar(120),
    constraint fk_diary_content_block_diary
        foreign key (diary_id) references diaries(id)
        on delete cascade
);

create index if not exists idx_diary_content_blocks_diary_order
    on diary_content_blocks(diary_id, display_order);
