create table if not exists sse_stream_tickets (
    ticket varchar(120) primary key,
    stream_type varchar(40) not null,
    member_id bigint not null,
    expires_at varchar(40) not null,
    consumed_at varchar(40),
    constraint fk_sse_stream_ticket_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_sse_stream_tickets_member_type
    on sse_stream_tickets(member_id, stream_type, expires_at);

create table if not exists sse_stream_sessions (
    id varchar(120) primary key,
    stream_type varchar(40) not null,
    member_id bigint not null,
    instance_id varchar(120) not null,
    connected_at varchar(40) not null,
    expires_at varchar(40) not null,
    closed_at varchar(40),
    constraint fk_sse_stream_session_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_sse_stream_sessions_member_type
    on sse_stream_sessions(member_id, stream_type, closed_at, expires_at);

create table if not exists sse_stream_events (
    id bigint generated by default as identity primary key,
    stream_type varchar(40) not null,
    member_id bigint not null,
    event_name varchar(120) not null,
    data clob not null,
    created_at varchar(40) not null,
    constraint fk_sse_stream_event_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_sse_stream_events_id
    on sse_stream_events(id);

create index if not exists idx_sse_stream_events_member_type
    on sse_stream_events(member_id, stream_type, id);
