create table if not exists member_data_exports (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    status varchar(30) not null,
    requested_at varchar(40) not null,
    completed_at varchar(40),
    expires_at varchar(40),
    downloaded_at varchar(40),
    failure_reason varchar(500),
    content_json text,
    constraint fk_member_data_export_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_member_data_exports_member_requested
    on member_data_exports(member_id, requested_at);
