create table if not exists content_moderation_audit_events (
    id bigint generated by default as identity primary key,
    member_id bigint,
    target varchar(40) not null,
    allowed boolean not null,
    risk_level varchar(40) not null,
    categories text not null,
    model_status varchar(40) not null,
    latency_ms bigint not null,
    text_hash varchar(64) not null,
    text_length integer not null,
    content_summary text not null,
    created_at varchar(40) not null,
    constraint fk_content_moderation_audit_member
        foreign key (member_id) references auth_members(id)
        on delete set null
);

create index if not exists idx_content_moderation_audit_created
    on content_moderation_audit_events(created_at);

create index if not exists idx_content_moderation_audit_target_created
    on content_moderation_audit_events(target, created_at);

create index if not exists idx_content_moderation_audit_model_status
    on content_moderation_audit_events(model_status, created_at);
