create table if not exists auth_signup_email_verifications (
    id bigint generated by default as identity primary key,
    email varchar(320) not null,
    code_hash varchar(128) not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    failed_attempts integer not null default 0,
    created_at timestamp with time zone not null
);

create index if not exists idx_auth_signup_email_verifications_email_active
    on auth_signup_email_verifications(email, consumed_at, expires_at);
