create table if not exists auth_members (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    password_hash varchar(255) not null,
    nickname varchar(80) not null,
    random_receive_allowed boolean not null default true,
    social_account boolean not null default false,
    role varchar(30) not null,
    status varchar(30) not null
);

create table if not exists auth_refresh_tokens (
    refresh_token varchar(512) primary key,
    member_id bigint not null,
    created_at varchar(40) not null,
    constraint fk_auth_refresh_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create table if not exists diaries (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    nickname varchar(80) not null,
    title varchar(255) not null,
    content clob not null,
    category_name varchar(80) not null,
    image_url varchar(1000),
    is_private boolean not null,
    create_date varchar(40) not null,
    modify_date varchar(40) not null,
    constraint fk_diary_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_diaries_member_created
    on diaries(member_id, create_date);

create table if not exists story_posts (
    id bigint generated by default as identity primary key,
    author_id bigint not null,
    author_nickname varchar(80) not null,
    title varchar(255) not null,
    content clob not null,
    category varchar(40) not null,
    resolution_status varchar(40) not null,
    view_count integer not null,
    thumbnail varchar(1000),
    create_date varchar(40) not null,
    modify_date varchar(40) not null,
    constraint fk_story_post_author
        foreign key (author_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_story_posts_created
    on story_posts(create_date);

create table if not exists story_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    author_id bigint not null,
    author_nickname varchar(80) not null,
    author_email varchar(320) not null,
    parent_comment_id bigint,
    content clob not null,
    create_date varchar(40) not null,
    modify_date varchar(40) not null,
    constraint fk_story_comment_post
        foreign key (post_id) references story_posts(id)
        on delete cascade,
    constraint fk_story_comment_author
        foreign key (author_id) references auth_members(id)
        on delete cascade,
    constraint fk_story_comment_parent
        foreign key (parent_comment_id) references story_comments(id)
        on delete cascade
);

create index if not exists idx_story_comments_post_created
    on story_comments(post_id, create_date);

create table if not exists letters (
    id bigint generated by default as identity primary key,
    sender_id bigint not null,
    sender_nickname varchar(80) not null,
    title varchar(255) not null,
    content clob not null,
    status varchar(40) not null,
    reply_content clob,
    created_date varchar(40) not null,
    reply_created_date varchar(40),
    constraint fk_letter_sender
        foreign key (sender_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_letters_sender_created
    on letters(sender_id, created_date);

create table if not exists letter_rejections (
    letter_id bigint not null,
    member_id bigint not null,
    primary key (letter_id, member_id),
    constraint fk_letter_rejection_letter
        foreign key (letter_id) references letters(id)
        on delete cascade,
    constraint fk_letter_rejection_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    receiver_id bigint not null,
    content clob not null,
    is_read boolean not null default false,
    created_at varchar(40) not null,
    constraint fk_notification_receiver
        foreign key (receiver_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_notifications_receiver_created
    on notifications(receiver_id, created_at);

create table if not exists reports (
    id bigint generated by default as identity primary key,
    reporter_id bigint not null,
    target_id bigint not null,
    target_type varchar(40) not null,
    reason varchar(40) not null,
    content clob,
    status varchar(40) not null,
    created_at varchar(40) not null,
    constraint fk_reporter_member
        foreign key (reporter_id) references auth_members(id)
        on delete cascade,
    constraint uq_reporter_target
        unique (reporter_id, target_id, target_type)
);

create table if not exists consultation_sessions (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    created_at varchar(40) not null,
    updated_at varchar(40) not null,
    constraint fk_consultation_session_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create table if not exists consultation_messages (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    sender varchar(40) not null,
    content clob not null,
    created_at varchar(40) not null,
    constraint fk_consultation_message_session
        foreign key (session_id) references consultation_sessions(id)
        on delete cascade
);
