create table if not exists image_assets (
    id bigint generated by default as identity primary key,
    owner_member_id bigint not null,
    url varchar(1000) not null unique,
    storage_key varchar(1000) not null,
    original_filename varchar(255) not null,
    content_type varchar(120) not null,
    byte_size bigint not null,
    status varchar(40) not null,
    target_type varchar(40),
    target_id bigint,
    created_at varchar(40) not null,
    updated_at varchar(40) not null,
    constraint fk_image_asset_owner
        foreign key (owner_member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_image_assets_owner_status
    on image_assets(owner_member_id, status);

create index if not exists idx_image_assets_target
    on image_assets(target_type, target_id);
