create table if not exists auth_oidc_states (
    id bigint generated by default as identity primary key,
    provider varchar(40) not null,
    state varchar(160) not null unique,
    nonce varchar(160) not null,
    code_verifier varchar(160) not null,
    redirect_uri varchar(1000) not null,
    expires_at varchar(40) not null,
    consumed_at varchar(40),
    created_at varchar(40) not null
);

create index if not exists idx_auth_oidc_states_expires
    on auth_oidc_states(expires_at);
