alter table consultation_messages
    add column if not exists sensitive boolean not null default false;

alter table consultation_messages
    add column if not exists retention_until varchar(40);

alter table consultation_messages
    add column if not exists hidden boolean not null default false;

create index if not exists idx_consultation_messages_sensitive
    on consultation_messages(sensitive, hidden);

create table if not exists consultation_safety_audit_events (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    category varchar(40) not null,
    severity varchar(40) not null,
    action_policy varchar(40) not null,
    message_preview clob not null,
    created_at varchar(40) not null,
    constraint fk_consultation_safety_audit_member
        foreign key (member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_consultation_safety_audit_member_created
    on consultation_safety_audit_events(member_id, created_at);
