create table if not exists admin_audit_events (
    id bigint generated by default as identity primary key,
    target_member_id bigint not null,
    actor_member_id bigint not null,
    action varchar(60) not null,
    previous_value clob not null,
    new_value clob not null,
    reason clob not null,
    created_at varchar(40) not null,
    constraint fk_admin_audit_target_member
        foreign key (target_member_id) references auth_members(id)
        on delete cascade,
    constraint fk_admin_audit_actor_member
        foreign key (actor_member_id) references auth_members(id)
        on delete cascade
);

create index if not exists idx_admin_audit_target_created
    on admin_audit_events(target_member_id, created_at);
