spring:
  datasource:
    url: jdbc:h2:file:./data/maum-on-mobile;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

app:
  images:
    local:
      root: ./data/images
      public-base-path: /images/uploads
