name: maum_on_mobile_front
description: Android and iOS Flutter app for Maum On.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  app_links: ^7.0.0
  dio: ^5.9.0
  file_picker: ^3.0.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
